### ISSUE TITLE
append new csv data

### ISSUE THREAD

**Issue by git-tiger** [zblesk/csv-to-sqlite#19]
Does the script handle appending new lines of csv?
We have a csv that is daily increasing with data.
If I run csv-to-sqlite, would it know to only add the new entries?

**Comment by zblesk** [comment]
If you disable dropping tables, the script should add all rows from a csv into existing ones, if they match. 
If you're asking if the script does somehow calculate a diff so that it would _only_ import the _new_ ones, then no, it doesn't. You can just run it with the 'drop tables' option and re-create the entire DB from the file, though.
