### ISSUE TITLE
'encoding' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by saitawngpha** [zblesk/csv-to-sqlite#2]
Dear,

Thank you for your sharing script. I have a tinny problem while I am trying to convert CSV file to Sqlite database. Please look at from the photo below.
![image](https://user-images.githubusercontent.com/9567660/35214488-b73915b8-ff8f-11e7-802e-a9f6bab869b6.png)

I need you help, how to solve this error.
Best,
STP

**Comment by zblesk** [comment]
Hello. I'll try to look into it, but I'm not sure when I'll find the time. 

In the meantime: could you please upload a sample of the file that causes this error? 

Thanks.

**Comment by saitawngpha** [comment]
Dear, 
Thanks for your replied and please look at the CSV file from the link below.

[tai_dict.zip](https://github.com/zblesk/csv-to-sqlite/files/1654564/tai_dict.zip)

I had run the setup file as you shown in the tutorial guide. And I had tried both of Mac and Windows 10 OS but I have still got the same error like the photo above.

Best,
STP

**Comment by zblesk** [comment]
I have tried it, and it worked perfectly, with exactly your parameters. (I ran under Windows 10.)  

How did you install it? Did you use pip? (It seems like you perhaps cloned the repo and ran it manually?)

**Comment by saitawngpha** [comment]
I had download from the repo, and run setup.py file. After that, run it. I have also using Windows 10 and where do I have to start?

**Comment by saitawngpha** [comment]
I had download from the repo, and run setup.py file. After that, run it. I have also using Windows 10 and where do I have to start?

**Comment by zblesk** [comment]
You should install with pip: `pip install csv-to-sqlite`. 
That will install a command called `csv-to-sqlite`. You can then run that directly (i.e. instead of `python csv_to_sqlite.py`). 

I tested on Windows, Bash on Windows and Ubuntu, and they all seem to work. 

Could you please try the pip install again and let me know? Thanks.

(I made a minor update yesterday and switched from setuptools to flit, so `setup.py` isn't even in the repo anymore.)
