### ISSUE TITLE
Why not Lazy?

### ISSUE THREAD

**Issue by mosynaq** [zblesk/csv-to-sqlite#5]
I love this script, but it can get much better if it could write records one by one from .csv file into the SQLite file. This approach is especially useful when a huge .csv file should be converted. Reading all records into RAM and then writing them a batch mode is not good for huge .csv files, like my case.

**Comment by zblesk** [comment]
Well, the prosaic answer to "why not" is because nobody implemented it yet. 
It is the way it is now because it first reads every line in order to determine the column types (so it gets it correctly even if there is a column with 100 integers, with a string in the last row). 

One would have to skip getting the typings, or generate them just by the first row and accept any errors, or read the file in two passes. 

Since you're not the first to request this, I might do it when I have the time; or feel free to send a PR.

**Comment by zblesk** [comment]
Should be fixed in the next version.
